name: jokes_flutter
description: Chuck Norris Jokes

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.5
  http: ^0.12.0+2
  pull_to_refresh: ^1.4.3
  strings: 0.1.0
  quiver: ^2.0.3
  html_unescape: 1.0.1+2
  flutter_html_widget: 0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/chuck.jpg
  - assets/smile.png
