name: Chuck Norris Jokes
description: Chuck Norris Jokes

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  http: 0.11.3+17
  pull_to_refresh: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true